/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author ASUS
 */
public class SearchData extends javax.swing.JFrame {
    char Alphabet;
    int i;
    /**
     * Creates new form SearchData
     */
    public SearchData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Judul = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        NamaInput = new javax.swing.JLabel();
        NIMInput = new javax.swing.JLabel();
        Fieldinputnama = new javax.swing.JTextField();
        FieldInputNIM = new javax.swing.JTextField();
        OutputNama = new javax.swing.JLabel();
        NIMOutput = new javax.swing.JLabel();
        FieldOutputNama = new java.awt.TextField();
        FieldNIMOutput = new java.awt.TextField();
        RunButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        LoopNama = new java.awt.TextField();
        LoopNIM = new java.awt.TextField();
        KetSearchNama = new java.awt.TextField();
        KetSearchNIM = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(27, 38, 44));
        jPanel2.setBackground(new java.awt.Color(15, 76, 129));

        Judul.setFont(new java.awt.Font("Montserrat Black", 0, 40)); // NOI18N
        // Judul.setTextColor(new java.awt.Color(255, 255, 255));
        Judul.setText("Data Searching");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        NamaInput.setFont(new java.awt.Font("Roboto", 0, 12));
        NamaInput.setText("Nama");

        NIMInput.setFont(new java.awt.Font("Roboto", 0, 12));
        NIMInput.setText("NIM");

        Fieldinputnama.setText("ABCD");
        Fieldinputnama.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                FieldinputnamaPerformed(evt);
            }
        });

        FieldInputNIM.setText("234");
        FieldInputNIM.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                FieldInputNimPerformed(evt);
            }
        });

        OutputNama.setText("Nama");

        NIMOutput.setText("NIM");

        FieldOutputNama.setText("");
        FieldOutputNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FieldOutputNama.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                FieldOutputNamaActionPerformed(evt);
            }
        });

        FieldNIMOutput.setText("");
        FieldNIMOutput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        FieldNIMOutput.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                FieldNIMOutputActionPerformed(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                RunButtonHasClicked(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                ClearButtonHasClicked(evt);
            }
        });

        LoopNama.setText("");

        LoopNIM.setText("");

        KetSearchNama.setText("");

        KetSearchNIM.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NamaInput, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addComponent(NIMInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(OutputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NIMOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RunButton)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FieldNIMOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldOutputNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FieldInputNIM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addComponent(Fieldinputnama, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LoopNama, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoopNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(KetSearchNama, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(KetSearchNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ClearButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaInput)
                    .addComponent(Fieldinputnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIMInput)
                    .addComponent(FieldInputNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OutputNama)
                    .addComponent(FieldOutputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoopNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KetSearchNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NIMOutput)
                            .addComponent(FieldNIMOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KetSearchNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RunButton)
                            .addComponent(ClearButton)))
                    .addComponent(LoopNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                                   

    /**
     * @param args the command line arguments
     */

    private void FieldinputnamaPerformed(java.awt.event.ActionEvent evt){

    }

    private void FieldInputNimPerformed(java.awt.event.ActionEvent evt){
        
    }

    private void RunButtonHasClicked(java.awt.event.ActionEvent evt){
        String myName = Fieldinputnama.getText();
        String myNIM = FieldInputNIM.getText();

        // Fieldinputnama.setText("");
        // FieldInputNIM.setText("");

        char[] CharNama = myName.toCharArray();
        char[] CharAngka = myNIM.toCharArray();

        char[] namecatch = new char[myName.length()];
        char[] nimcatch = new char[myName.length()];

        try{
            String catching = " ";
            String take = "";
            for (int a = 0; a<myName.length(); a++){
                namecatch[a] = CharNama[a];
                String eachfont = Character.toString(namecatch[a]);
                if(a != 0)
                    catching = catching + CharNama[a-1];
                for (int i = 65; i < 123; i++) {
                    this.setVisible(true);
                    KetSearchNama.setText("");
                    Alphabet = (char) i;
                    LoopNama.setText(""+Alphabet);//a
                    Thread.sleep(400);

                    if(Alphabet == CharNama[a])
                    {
                        Thread.sleep(50);
                        KetSearchNama.setText("Karakter Diterima");
                        Thread.sleep(1000);
                        LoopNama.setText("");
                        FieldOutputNama.setText(""+ catching + Alphabet);
                        break;
                    }
                    else
                    {
                        KetSearchNama.setText("Karakter Ditolak ");
                        Thread.sleep(300);
                        KetSearchNama.setText("");
                        Thread.sleep(300); 
                    }
                }
            }
            KetSearchNama.setText("String Dikenali ");
            
            for (int a = 0; a<myNIM.length(); a++){
                
                nimcatch[a] = CharAngka[a];
                String eachnu = Character.toString(nimcatch[a]);
                if(a != 0)
                    take = take + CharAngka[a-1];
                for (int i = 48; i < 57; i++) {
                    this.setVisible(true);
                    Alphabet = (char) i;
                    KetSearchNIM.setText("");
                    LoopNIM.setText(""+Alphabet);
                    Thread.sleep(400);
                    
                    if(Alphabet == CharAngka[a])
                    {
                        Thread.sleep(50);
                        KetSearchNIM.setText("Karakter Diterima");
                        Thread.sleep(1000);
                        LoopNIM.setText("");
                        FieldNIMOutput.setText(""+ take + Alphabet);
                        break;   
                    }
                    else
                    {
                        KetSearchNIM.setText("Karakter Ditolak ");
                        Thread.sleep(300);
                        KetSearchNIM.setText("");
                        Thread.sleep(300); 
                    }
                    
                }
            }
            KetSearchNIM.setText("String Dikenali");
            
        }
        catch(InterruptedException ex){
            ex.printStackTrace();
        }

    }

    private void FieldNIMOutputActionPerformed(java.awt.event.ActionEvent evt){

    }

    private void FieldOutputNamaActionPerformed(java.awt.event.ActionEvent evt){

    }

    private void ClearButtonHasClicked(java.awt.event.ActionEvent evt){
        Fieldinputnama.setText("");
        FieldInputNIM.setText("");
        FieldOutputNama.setText("");
        FieldNIMOutput.setText("");
        LoopNIM.setText("");
        LoopNama.setText("");
        KetSearchNIM.setText("");
        KetSearchNama.setText("");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField FieldInputNIM;
    private java.awt.TextField FieldNIMOutput;
    private java.awt.TextField FieldOutputNama;
    private javax.swing.JTextField Fieldinputnama;
    private java.awt.TextField KetSearchNIM;
    private java.awt.TextField KetSearchNama;
    private java.awt.TextField LoopNIM;
    private java.awt.TextField LoopNama;
    private javax.swing.JLabel NIMInput;
    private javax.swing.JLabel NIMOutput;
    private javax.swing.JLabel NamaInput;
    private javax.swing.JLabel OutputNama;
    private javax.swing.JButton RunButton;
    private javax.swing.JLabel Judul;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration                   
}
